language: python
python:
- "3.7"
before_install:
- mv travis-secrets.yaml secrets.yaml
- mv travis-gcp_service_account.json gcp_service_account.json
- sudo mkdir /config
- touch home-assistant_v2.db
- sudo apt-get install -y libudev-dev
install:
- pip3 install homeassistant
script:
- hass -c . --script check_config
