language: python
python:
- "3.9.1"
before_install:
- mv travis-secrets.yaml secrets.yaml
- mv travis-gcp_service_account.json gcp_service_account.json
- sudo mkdir /config
- sudo apt-get install -y libudev-dev
- pip install importlib-metadata==4.12
install:
- pip3 install homeassistant
script:
- hass -c . --script check_config
