- id: '1616205706096'
  alias: 'Button Livingroom '
  description: Zigbee button automation for controlling the living-room lights
  use_blueprint:
    path: sonoff_zigbee_button.yaml
    input:
      sonoff_button: 0c1650775cfd16aae9edc5fe05ed5bad
      toggle_action:
      - service: light.toggle
        data:
          brightness_pct: 50
          transition: 3
        target:
          device_id: 1dd4cc1394caee32c5ccefeb7bcb41ba
      on_action:
      - service: light.toggle
        data:
          brightness_pct: 50
          transition: 3
        target:
          device_id: 29c9deb2ac22847633172b53b98ff907
      off_action:
      - service: scene.turn_on
        target:
          entity_id: scene.lights_off
        data: {}
- id: '1616275227538'
  alias: Motion Sensor Kitchen
  description: Motion-activated Kitchen Light
  use_blueprint:
    path: motion_activated_switch.yaml
    input:
      motion_entity: binary_sensor.motion_kitchen_ias_zone
      switch_target:
        entity_id: switch.kitchen_light
      below_elevation: 5
      no_motion_wait: 300
- id: '1625700474272'
  alias: 'Button Hallway '
  description: Sonoff Zigbee Button for Hallway Light
  use_blueprint:
    path: sonoff_zigbee_button.yaml
    input:
      sonoff_button: 2a6f68fca7c2d52287aaafb256bb5af0
      toggle_action:
      - service: light.toggle
        target:
          device_id: f89e5f7d50af4e82e02adf723671248f
        data:
          brightness_pct: 80
      off_action:
      - service: scene.turn_on
        target:
          entity_id: scene.lights_off
        metadata: {}
      on_action:
      - service: scene.turn_on
        target:
          entity_id: scene.low_light_living_room
        metadata: {}
- id: '1648505989977'
  alias: ' Motion Sensor Study'
  description: Automation to control the lights in Ishan's study
  use_blueprint:
    path: motion_activated_light_or_switch.yaml
    input:
      motion_entity: binary_sensor.motion_sensor_study_ias_zone
      no_motion_wait: 5
      below_elevation: 7
      target_entity: light.study_led_rgb
- id: '1650157894092'
  alias: TV Wake On LAN
  description: Automation to send a wake-on-lan magic packet every time the lgwebos
    turn_on service is called.
  trigger:
  - platform: device
    device_id: 2889ecd32fd5fae8af8798d468016011
    domain: webostv
    type: webostv.turn_on
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: B4:E6:2A:87:A8:52
  mode: single
- id: '1650329522998'
  alias: Plex Lighting
  description: ''
  trigger:
  - platform: device
    device_id: 222ba24bbee291d31445d155f0644945
    domain: media_player
    entity_id: media_player.plex_aurelia_plex_for_lg_lg_oled55e7n_z
    type: playing
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: or
    conditions:
    - condition: sun
      before: sunrise
    - condition: sun
      after: sunset
  action:
  - service: scene.create
    data:
      scene_id: temp_plex_scene
      snapshot_entities:
      - light.livingroom_floorlamp
      - light.livingroom_spotlight
      - switch.hallway_shelf_light
      - light.hallway_light
  - service: scene.turn_on
    target:
      entity_id: scene.plex_movie_scene
    data:
      transition: 2.5
  - wait_for_trigger:
    - platform: device
      type: changed_states
      device_id: 222ba24bbee291d31445d155f0644945
      entity_id: media_player.plex_aurelia_plex_for_lg_lg_oled55e7n_z
      domain: media_player
      for:
        hours: 0
        minutes: 0
        seconds: 5
    continue_on_timeout: false
  - service: scene.turn_on
    target:
      entity_id: scene.temp_plex_scene
    data:
      transition: 2.5
  mode: single
- id: '1650928264103'
  alias: Plex Series Notification
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.plex_library_series
  - platform: state
    entity_id: sensor.plex_library_movies
  condition: []
  action:
  - service: notify.tv
    data_template:
      message: 'Downloaded: {{ trigger.to_state.attributes.last_added_item }}'
  - service: notify.mobile_app_iphone_13_mini
    data_template:
      message: '{{ trigger.to_state.attributes.last_added_item }}'
      title: 'Plex: Series Downloaded!'
  mode: single
- id: '1665429843951'
  alias: Hallway Motion Sensor
  description: ''
  use_blueprint:
    path: motion_activated_light_or_switch.yaml
    input:
      motion_entity: binary_sensor.motion_sensor_hallway_iaszone
      target_entity: light.hallway_light
      no_motion_wait: 1
- id: '1667079325658'
  alias: 'CPU Temp Warning: 60C'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.system_temp
    above: 60
  condition: []
  action:
  - service: notify.alexa_media_echo_spot
    data:
      message: Home Assistant Warning! CPU Temperature has exceeded 60 degrees!
      data:
        type: tts
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.system_temp
      below: 60
  - service: notify.alexa_media_echo_spot
    data:
      message: Home Assistant CPU Temperature back to normal
      data:
        type: tts
  mode: single
- id: '1667082780494'
  alias: 'CPU Temp Warning: 70C'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.system_temp
    above: 70
  condition: []
  action:
  - service: notify.alexa_media_echo_spot
    data:
      message: Home Assistant Warning! CPU Temperature has exceeded 70 degrees!
      data:
        type: tts
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.system_temp
      below: 70
  - service: notify.alexa_media_echo_spot
    data:
      message: Home Assistant CPU Temperature is below 70 degrees
      data:
        type: tts
  mode: single
- id: '1667962528248'
  alias: Remote Control Study
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: 39c863e44fc4dd63c1b93f3a442e6cfa
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.endpoint_id == 1 and trigger.event.data.command
          == ''remote_button_short_press'' }}'
      sequence:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.ishan_s_desk_light
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command
          == ''remote_button_short_press'' }}'
      sequence:
      - service: light.toggle
        data: {}
        target:
          device_id: c96f64c92c075cef29f1f7da0113bcd3
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command
          == ''remote_button_double_press'' }}'
      sequence:
      - service: automation.toggle
        data: {}
        target:
          entity_id: automation.study_motion_sensor
      - if:
        - condition: state
          entity_id: automation.study_motion_sensor
          state: 'on'
        then:
        - service: light.turn_on
          data:
            flash: long
          target:
            device_id: c96f64c92c075cef29f1f7da0113bcd3
        else:
        - service: light.turn_off
          data: {}
          target:
            device_id: c96f64c92c075cef29f1f7da0113bcd3
  mode: single
- id: '1668461303942'
  alias: Auto Heating
  description: ''
  trigger:
  - platform: template
    value_template: "{% if states('sensor.living_room_sensor_temperature') | float(0)
      < 18.5 %}\n  true\n{% else %}\n  false\n{% endif %}\n"
    for:
      hours: 0
      minutes: 2
  condition:
  - condition: or
    conditions:
    - condition: zone
      entity_id: person.aurelia
      zone: zone.home
    - condition: zone
      entity_id: person.ishan
      zone: zone.home
  action:
  - service: switch.turn_on
    data: {}
    target:
      device_id: 9ea5fe09381290a36747ed5dc5a4d96d
  - wait_for_trigger:
    - platform: template
      value_template: "{% if states('sensor.living_room_sensor_temperature') | float(0)
        > 18.5 %}\n  true\n{% else %}\n  false\n{% endif %}\n"
      for:
        hours: 0
        minutes: 2
    continue_on_timeout: true
  - service: switch.turn_off
    data: {}
    target:
      device_id: 9ea5fe09381290a36747ed5dc5a4d96d
  mode: restart
