- id: '1615942832248'
  alias: Basic Notification
  description: Notification test
  trigger:
  - platform: state
    entity_id: person.ishan
    to: home
  condition: []
  action:
  - service: notify.mobile_app_iphone
    data:
      title: Welcome Home!
      message: Friendly message from your Home Assistant
  mode: single
- id: '1616205706096'
  alias: Button Livingroom Spotlight
  description: Zigbee button automation for controlling the living-room lights
  use_blueprint:
    path: sonoff_zigbee_button.yaml
    input:
      sonoff_button: 0c1650775cfd16aae9edc5fe05ed5bad
      toggle_action:
      - service: light.toggle
        data:
          brightness_pct: 50
        target:
          device_id: 53a0016bf728ed5cceabbe9d8b26ad70
      on_action:
      - service: light.toggle
        data:
          brightness_pct: 50
        target:
          device_id: 5f42190043df478db214df328a6d8c8b
      off_action:
      - service: scene.turn_on
        target:
          entity_id: scene.lights_off
- id: '1616275227538'
  alias: Kitchen Light
  description: Motion-activated Kitchen Light
  use_blueprint:
    path: motion_activated_switch.yaml
    input:
      motion_entity: binary_sensor.motion_kitchen_ias_zone
      switch_target:
        entity_id: switch.kitchen_light
      below_elevation: 5
      no_motion_wait: 300
- id: '1620860129873'
  alias: Ishan's Desk Sensor
  description: ''
  use_blueprint:
    path: motion_activated_switch.yaml
    input:
      switch_target:
        entity_id: switch.ishan_s_desk_light
      below_elevation: 7
      motion_entity: binary_sensor.motion_sensor_study_ias_zone
- id: '1625700474272'
  alias: Button Hallway Light
  description: Sonoff Zigbee Button for Hallway Light
  use_blueprint:
    path: sonoff_zigbee_button.yaml
    input:
      sonoff_button: 2a6f68fca7c2d52287aaafb256bb5af0
      toggle_action:
      - service: light.toggle
        target:
          device_id: f89e5f7d50af4e82e02adf723671248f
        data:
          brightness_pct: 50
