- id: '1616205706096'
  alias: Button Livingroom Spotlight
  description: Zigbee button automation for controlling the living-room lights
  use_blueprint:
    path: sonoff_zigbee_button.yaml
    input:
      sonoff_button: 0c1650775cfd16aae9edc5fe05ed5bad
      toggle_action:
      - service: light.toggle
        data:
          brightness_pct: 50
          transition: 3
        target:
          device_id: 2d8b6c36efa8f2c0a8041ba80ea0248c
      on_action:
      - service: light.toggle
        data:
          brightness_pct: 50
          transition: 3
        target:
          device_id: 29c9deb2ac22847633172b53b98ff907
      off_action:
      - service: scene.turn_on
        target:
          entity_id: scene.lights_off
- id: '1616275227538'
  alias: Kitchen Light
  description: Motion-activated Kitchen Light
  use_blueprint:
    path: motion_activated_switch.yaml
    input:
      motion_entity: binary_sensor.motion_kitchen_ias_zone
      switch_target:
        entity_id: switch.kitchen_light
      below_elevation: 5
      no_motion_wait: 300
- id: '1620860129873'
  alias: Ishan's Desk Sensor
  description: ''
  use_blueprint:
    path: motion_activated_switch.yaml
    input:
      switch_target:
        entity_id: switch.ishan_s_desk_light
      below_elevation: 7
      motion_entity: binary_sensor.motion_sensor_study_ias_zone
- id: '1625700474272'
  alias: Button Hallway Light
  description: Sonoff Zigbee Button for Hallway Light
  use_blueprint:
    path: sonoff_zigbee_button.yaml
    input:
      sonoff_button: 2a6f68fca7c2d52287aaafb256bb5af0
      toggle_action:
      - service: light.toggle
        target:
          device_id: f89e5f7d50af4e82e02adf723671248f
        data:
          brightness_pct: 50
- id: '1648505989977'
  alias: ' Study Motion Sensor'
  description: Automation to control the lights in Ishan's study
  use_blueprint:
    path: motion_activated_light_or_switch.yaml
    input:
      motion_entity: binary_sensor.motion_sensor_study_ias_zone
      no_motion_wait: 5
      below_elevation: 7
      target_entity: light.study_led_rgb
- id: '1650157894092'
  alias: TV Wake On LAN
  description: Automation to send a wake-on-lan magic packet every time the lgwebos
    turn_on service is called.
  trigger:
  - platform: device
    device_id: 2889ecd32fd5fae8af8798d468016011
    domain: webostv
    type: webostv.turn_on
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: B4:E6:2A:87:A8:52
  mode: single
