- alias: PC Desk Light Trigger ON
  trigger:
    platform: state
    entity_id: device_tracker.homeworkstation
    from: 'not_home'
    to: 'home'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: switch.turn_on
    entity_id: switch.ishan_s_desk_light
    
- alias: PC Desk Light Trigger OFF
  trigger:
    platform: state
    entity_id: device_tracker.homeworkstation
    from: 'home'
    to: 'not_home'
  action:
    service: switch.turn_off
    entity_id: switch.ishan_s_desk_light