- alias: PC Desk Light Trigger ON
  trigger:
    platform: state
    entity_id: device_tracker.homeworkstation
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: switch.turn_on
    entity_id: switch.ishan_s_desk_light
  id: 0346d38fd32f4010bf6d4c9e92a56598
- alias: PC Desk Light Trigger OFF
  trigger:
    platform: state
    entity_id: device_tracker.homeworkstation
    from: home
    to: not_home
  action:
    service: switch.turn_off
    entity_id: switch.ishan_s_desk_light
  id: 8b2361df90a249b79d37a6c3a7485b9e
- id: '1615942832248'
  alias: Basic Notification
  description: Notification test
  trigger:
  - platform: state
    entity_id: person.ishan
    to: home
  condition: []
  action:
  - service: notify.mobile_app_oneplus_a5000
    data:
      title: Hey
      message: You're home!
  mode: single
- id: '1616205706096'
  alias: Button Livingroom Spotlight
  description: Zigbee button automation for controlling the living-room lights
  use_blueprint:
    path: sonoff_zigbee_button.yaml
    input:
      sonoff_button: 0c1650775cfd16aae9edc5fe05ed5bad
      toggle_action:
      - service: light.toggle
        data:
          brightness_pct: 50
        target:
          device_id: 53a0016bf728ed5cceabbe9d8b26ad70
      on_action:
      - service: light.toggle
        data:
          brightness_pct: 50
        target:
          device_id: 5f42190043df478db214df328a6d8c8b
      off_action:
      - service: scene.turn_on
        target:
          entity_id: scene.low_light_living_room
- id: '1616268705098'
  alias: Motion Activated Kitchen Light (deprecated)
  description: Motion Activated Kitchen Light (use the blueprint instead)
  trigger:
  - type: occupied
    platform: device
    device_id: 86468a3ce7373daadce61e7afd5a295f
    entity_id: binary_sensor.motion_kitchen_occupancy
    domain: binary_sensor
  condition:
  - condition: sun
    after: sunset
    after_offset: -00:45:00
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.kitchen_light
  - wait_for_trigger:
    - type: not_occupied
      platform: device
      device_id: 86468a3ce7373daadce61e7afd5a295f
      entity_id: binary_sensor.motion_kitchen_occupancy
      domain: binary_sensor
    - device_id: 86468a3ce7373daadce61e7afd5a295f
      domain: zha
      platform: device
      type: device_offline
      subtype: device_offline
    continue_on_timeout: true
  - service: switch.turn_off
    target:
      entity_id: switch.kitchen_light
  mode: single
- id: '1616275227538'
  alias: Kitchen Light
  description: Motion-activated Kitchen Light
  use_blueprint:
    path: motion_activated_switch.yaml
    input:
      motion_entity: binary_sensor.motion_kitchen_2_ias_zone
      switch_target:
        entity_id: switch.kitchen_light
      below_elevation: 5
      no_motion_wait: 180
