homeassistant:
  name: Home
  latitude: 48.867929
  longitude: 2.416406
  elevation: 80
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config

# Configure a default setup of Home Assistant (frontend, api, etc)
frontend:
  themes: !include_dir_merge_named themes
default_config:

zha:
  database_path: /config/zigbee.db

webostv:
  host: 192.168.1.44
  name: Living Room TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: B4:E6:2A:87:A8:52
  customize:
    sources:
      - Amazon Prime Video
      - HDMI1
      - HDMI2
      - Netflix
      - Spotify - Music and Podcasts
      - YouTube
      - 'Freebox Server'

notify:
  - platform: webostv
    host: 192.168.1.44
    name: living_room_tv
    filename: webostv.conf

wake_on_lan:
media_player: #!include media_players.yaml

# https://www.home-assistant.io/docs/configuration/splitting_configuration/
switch: !include switches.yaml
    
sensor: !include sensors.yaml

http:
# https://community.home-assistant.io/t/trusted-networks-when-using-nginx-reverse-proxy/37836
  use_x_forwarded_for: true
  trusted_proxies: 192.168.1.67     # traefik machine IP
  ip_ban_enabled: True
  login_attempts_threshold: 3

# https://www.home-assistant.io/integrations/recorder/
recorder:
  db_url: mysql://homeassistant:homeassistant@192.168.1.67/homeassistant?charset=utf8mb4
  auto_purge: true
  purge_keep_days: 7
  commit_interval: 10
  exclude:
    domains:
      - automation
      - updater
      - media_player
      # - sensor
      # - device_tracker
    entities:
      - sun.sun
  # include:
  #   entities:
  #     - sensor.home_assistant_v2_db
  #     - sensor.freebox_temperature_cpu_cp_master
  #     - sensor.freebox_temperature_cpu_cp_slave

influxdb: !include influxdb.yaml

# Example configuration.yaml entry
google_assistant:
  project_id: home-assistant-b6745
  service_account: !include gcp_service_account.json
  report_state: true
#  entity_config:
#    switch.kitchen:
#      name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
#      aliases:
#        - BRIGHT_LIGHTS
#        - ENTRY_LIGHTS
#    light.living_room:
#      expose: false
#      room: LIVING_ROOM

homekit:
  auto_start: true
  filter:
    include_domains:
      - switch
      - light
      - sensor
      - media_player
    include_entity_globs:
      - binary_sensor.*_ias_zone
    exclude_entity_globs:
      - sensor.freebox_temperature*
      - sensor.gm1911*
      - sensor.oneplus*
    exclude_entities:
      - switch.deluge_switch
      - switch.freebox_wifi
      - media_player.bathroom_speakers

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
