homeassistant:
  name: Home
  latitude: 48.867929
  longitude: 2.416406
  elevation: 80
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config

#logger:
#  default: info
#  logs:
#    custom_components.myEnedis: debug

# Configure a default setup of Home Assistant (frontend, api, etc)
frontend:
  themes: !include_dir_merge_named themes
default_config:

zha:
  database_path: /config/zigbee.db

wake_on_lan:
media_player: #!include media_players.yaml

# Example configuration.yaml entry
# spotify:
#   client_id: !secret spotify_clientid
#   client_secret: !secret spotify_clientsecret

spotcast:
  sp_dc: !secret spotify_sp_dc
  sp_key: !secret spotify_sp_key

# https://www.home-assistant.io/docs/configuration/splitting_configuration/
switch: !include switches.yaml
    
sensor: !include sensors.yaml

http:
# https://community.home-assistant.io/t/trusted-networks-when-using-nginx-reverse-proxy/37836
  use_x_forwarded_for: true
  trusted_proxies: 192.168.1.67     # traefik machine IP
  ip_ban_enabled: True
  login_attempts_threshold: 3

# https://www.home-assistant.io/integrations/recorder/
recorder:
  db_url: mysql://homeassistant:homeassistant@192.168.1.67/homeassistant?charset=utf8mb4
  auto_purge: true
  purge_keep_days: 7
  commit_interval: 10
  exclude:
    domains:
      - automation
      - updater
      - media_player
      # - sensor
      # - device_tracker
    entity_globs:
      - sensor.iphone*
      - sensor.oneplus*
    entities:
      - sun.sun

influxdb: !include influxdb.yaml

homekit:
  auto_start: true
  filter:
    include_domains:
      - switch
      - light
      - sensor
      - media_player
    include_entity_globs:
      - binary_sensor.*_ias_zone
    exclude_entity_globs:
      - sensor.freebox_temperature*
      - sensor.gm1911*
      - sensor.oneplus*
      - sensor.iphone*
    exclude_entities:
      - switch.deluge_switch
      - switch.freebox_wifi
      - media_player.bathroom_speakers
      - switch.kitchen_light

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
