# cert expiry doesn't work with SSL termination on reverse proxy (hassio.feignman.duckdns.org)
#- platform: cert_expiry
#  host: feignman-home.duckdns.org
#  port: 8123
- platform: spotcast
- platform: command_line
  name: System Temp
  command: "awk '{print $1/1000}' /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
- platform: command_line
  name: Free Memory
  command: "awk '/MemAvailable/{print $(NF-1)/1000}' /proc/meminfo"
  unit_of_measurement: "MB"
- platform: systemmonitor
  resources:
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: load_1m
      - type: processor_use
      - type: processor_temperature
- platform: template
  sensors:
    washer_state:
      friendly_name: 'Washer State'
      value_template: >-
        {% if is_state_attr('sensor.washer_dryer', 'run_state', "Lavage") %}
          {{ state_attr('sensor.washer_dryer', 'run_state') + ": " + state_attr('sensor.washer_dryer', 'current_course') + " [" + state_attr('sensor.washer_dryer', 'water_temp') + "]" }}
        {% else %}
          {{ state_attr('sensor.washer_dryer', 'run_state') }}
        {% endif %}
      icon_template: mdi:washing-machine
    washer_program_length:
      friendly_name: 'Washer Program Length'
      value_template: >-
        {% set washerprogramminutes = (state_attr('sensor.washer_dryer', 'initial_time').split(':')[0] | int * 60) + (state_attr('sensor.washer_dryer', 'initial_time').split(':')[1] | int) %}
        {{ washerprogramminutes }}
      icon_template: mdi:washing-machine
    washer_remaining_time:
      friendly_name: 'Washer Remaining Time'
      value_template: >-
        {% set washerremainminutes = (state_attr('sensor.washer_dryer', 'remain_time').split(':')[0] | int * 60) + (state_attr('sensor.washer_dryer', 'remain_time').split(':')[1] | int) %}
        {% if is_state_attr('sensor.washer_dryer', 'run_state', "Lavage") %}
          {{ washerremainminutes }}
        {% else %}
          {% if is_state_attr('sensor.washer_dryer', 'run_state', "Rinçage") %}
            {{ washerremainminutes }}
          {% else %}
            0
          {% endif %}
        {% endif %}
      icon_template: mdi:washing-machine
    washer_progress:
      friendly_name: 'Washer Progress'
      value_template: >-
        {% if states('sensor.washer_program_length') in ("unavailable", "unknown") or (states('sensor.washer_program_length') | int) < 1 %}
          0
        {% else %}
          {% set washerprogress = (100 - (((states('sensor.washer_remaining_time') | int) / (states('sensor.washer_program_length') | int)) * 100)) %}
          {% if is_state_attr('sensor.washer_dryer', 'run_state', "Lavage") %}
            {{ washerprogress }}
          {% else %}
            {% if is_state_attr('sensor.washer_dryer', 'run_state', "Rinçage") %}
              {{ washerprogress }}
            {% else %}
              0
            {% endif %}
          {% endif %}
        {% endif %}
      icon_template: mdi:washing-machine
    washspinner_state:
      friendly_name: 'Spinner Program'
      value_template: >-
        {% if is_state_attr('sensor.washer_dryer', 'run_state', "Essorage") %}
          {{ 'Spinning: ' + state_attr('sensor.washer_dryer', 'spin_speed') }}
        {% else %}
          {{ state_attr('sensor.washer_dryer', 'spin_speed') }}
        {% endif%}
      icon_template: mdi:washing-machine
    washspinner_remaining_time:
      friendly_name: 'Spinner Remaining Time'
      value_template: >-
        {% if is_state_attr('sensor.washer_dryer', 'run_state', "Essorage") %}
          {% set spinnerremainminutes = (state_attr('sensor.washer_dryer', 'remain_time').split(':')[0] | int * 60) + (state_attr('sensor.washer_dryer', 'remain_time').split(':')[1] | int) %}
          {{ spinnerremainminutes }}
        {% else %}
          0
        {% endif %}
      icon_template: mdi:washing-machine
    washspinner_progress:
      friendly_name: 'Spinner Progress'
      value_template: >-
        {% if states('sensor.washer_program_length') in ("unavailable", "unknown") or (states('sensor.washer_program_length') | int) < 1 %}
          0
        {% else %}
          {% if is_state_attr('sensor.washer_dryer', 'run_state', "Essorage") %}
            {% set spinnerprogress = (100 - (((states('sensor.washspinner_remaining_time') | int) / (states('sensor.washer_program_length') | int)) * 100)) %}
            {{ spinnerprogress }}
          {% else %}
            0
          {% endif %}
        {% endif %}
      icon_template: mdi:washing-machine
    dryer_state:
      friendly_name: 'Dryer Program'
      value_template: >-
        {{ state_attr('sensor.washer_dryer', 'dry_level') }}
      icon_template: mdi:washing-machine
    dryer_remaining_time:
      friendly_name: 'Dryer Remaining Time'
      value_template: >-
        {% if ((states.sensor.washer_dryer.attributes.run_state) == "Séchage") %}
          {% set dryerremainminutes = (state_attr('sensor.washer_dryer', 'remain_time').split(':')[0] | int * 60) + (state_attr('sensor.washer_dryer', 'remain_time').split(':')[1] | int) %}
          {{ dryerremainminutes }}
        {% else %}
          0
        {% endif %}
      icon_template: mdi:washing-machine
    dryer_progress:
      friendly_name: 'Dryer Progress'
      value_template: >-
        {% if states('sensor.washer_program_length') in ("unavailable", "unknown") or (states('sensor.washer_program_length') | int) < 1 %}
          0
        {% else %}
          {% if is_state_attr('sensor.washer_dryer', 'run_state', "Séchage") %}
            {% set dryerprogress = (100 - (((states('sensor.dryer_remaining_time') | int) / (states('sensor.washer_program_length') | int)) * 100)) %}
            {{ dryerprogress }}
          {% else %}
            0
          {% endif %}
        {% endif %}
      icon_template: mdi:washing-machine