#- platform: cert_expiry
#  host: hassio.feignman.duckdns.org
#  port: 8123
- platform: deluge
  host: 192.168.1.67
  port: 58846
  username: !secret deluge_user
  password: !secret deluge_pwd
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
- platform: filesize
  file_paths:
    - home-assistant_v2.db