# cert expiry doesn't work with SSL termination on reverse proxy (hassio.feignman.duckdns.org)
#- platform: cert_expiry
#  host: feignman-home.duckdns.org
#  port: 8123
- platform: spotcast
- platform: command_line
  name: System Temp
  command: "awk '{print $1/1000}' /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
- platform: command_line
  name: Free Memory
  command: "awk '/MemAvailable/{print $(NF-1)/1000}' /proc/meminfo"
  unit_of_measurement: "MB"
- platform: systemmonitor
  resources:
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: load_1m
      - type: processor_use
      - type: processor_temperature
