- platform: template
  switches:
    kitchen_light_control:
      friendly_name: "Kitchen Light"
      unique_id: "kitchen_light_control"
      value_template: "{{ is_state('switch.kitchen_light', 'on') }}"
      # availability_template: "{{ states.switch.kitchen_light.state == 'on' }}"
      turn_on:
        - service: switch.turn_on
          target:
            entity_id: switch.kitchen_light
        - service: automation.turn_off
          data: {}
          target:
            entity_id: automation.kitchen_light
      turn_off:
        - service: switch.turn_off
          target:
            entity_id: switch.kitchen_light
        - service: automation.turn_on
          data: {}
          target:
            entity_id: automation.kitchen_light
